apiVersion: v1
kind: Pod
metadata:
  name: shivam-privilege-app
  namespace: default
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 9999']
    securityContext:
       privileged: true
