apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: kube-logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      json {
        source => "message"
      }
      mutate {
        remove_field => ["message"]
      }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          index => "tetragon-json"
      }
    }